# Generated by Django 5.0.3 on 2024-04-27 07:15

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AnalysisRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField(blank=True, null=True)),
                ("file", models.FileField(upload_to="analysis_files/")),
                ("uuid", models.UUIDField(default=uuid.uuid4, editable=False)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("progress", "In Progress"),
                            ("queue", "Queued"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                        ],
                        default="queue",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "result",
                    models.FileField(
                        blank=True, null=True, upload_to="analysis_results/"
                    ),
                ),
                (
                    "email_sent",
                    models.BooleanField(blank=True, default=False, null=True),
                ),
            ],
        ),
    ]
