version: '3.8'

services:
  redis:
    image: redis:alpine
    container_name: plait_redis
    ports:
      - "6380:6379"
    volumes:
      - ./redisdata:/data

  web:
    build: .
    ports:
      - "8020:8020"
    env_file:
      - ./.env
    depends_on:
      - redis

networks:
  backend_network:
